"""add retraction table

Revision ID: 03ed48e49803
Revises: 67b3f402bf2b
Create Date: 2019-01-31 13:41:26.089551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ed48e49803'
down_revision = '67b3f402bf2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('retractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_doi', sa.String(length=255), nullable=True),
    sa.Column('compound_name', sa.String(length=255), nullable=True),
    sa.Column('compound_inchikey', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('retractions')
    # ### end Alembic commands ###
