"""empty message

Revision ID: 0ead85f53d27
Revises: 893ffe555025
Create Date: 2018-10-24 15:53:29.541194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ead85f53d27'
down_revision = '893ffe555025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'notes')
    # ### end Alembic commands ###
