"""add checker_article

Revision ID: 1857ed50f51e
Revises: 42b42f0a7d24
Create Date: 2019-01-21 11:37:53.631112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1857ed50f51e'
down_revision = '42b42f0a7d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checker_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Integer(), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('npa_artid', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('volume', sa.String(length=255), nullable=True),
    sa.Column('issue', sa.String(length=255), nullable=True),
    sa.Column('pages', sa.String(length=255), nullable=True),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checker_article')
    # ### end Alembic commands ###
