"""empty message

Revision ID: 249eaa378008
Revises: a5f45e16bb38
Create Date: 2018-10-22 14:13:44.378753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '249eaa378008'
down_revision = 'a5f45e16bb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compound', sa.Column('new_compound', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('compound', 'new_compound')
    # ### end Alembic commands ###
