"""empty message

Revision ID: 29e73bf8196d
Revises: 
Create Date: 2018-08-23 14:22:43.802332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e73bf8196d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Integer(), nullable=True),
    sa.Column('journal', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('volume', sa.String(length=255), nullable=True),
    sa.Column('issue', sa.String(length=255), nullable=True),
    sa.Column('pages', sa.String(length=255), nullable=True),
    sa.Column('authors', sa.String(length=255), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('num_compounds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('smiles', sa.String(length=1000), nullable=True),
    sa.Column('source_organism', sa.String(length=255), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.Column('csid', sa.Integer(), nullable=True),
    sa.Column('cbid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curator_email'), 'curator', ['email'], unique=True)
    op.create_index(op.f('ix_curator_first_name'), 'curator', ['first_name'], unique=False)
    op.create_index(op.f('ix_curator_last_name'), 'curator', ['last_name'], unique=False)
    op.create_index(op.f('ix_curator_username'), 'curator', ['username'], unique=True)
    op.create_table('article_compound',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('compound_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['compound_id'], ['compound.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'compound_id')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curator_id', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('last_edit_date', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['curator_id'], ['curator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_article',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('dataset_id', 'article_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_article')
    op.drop_table('dataset')
    op.drop_table('article_compound')
    op.drop_index(op.f('ix_curator_username'), table_name='curator')
    op.drop_index(op.f('ix_curator_last_name'), table_name='curator')
    op.drop_index(op.f('ix_curator_first_name'), table_name='curator')
    op.drop_index(op.f('ix_curator_email'), table_name='curator')
    op.drop_table('curator')
    op.drop_table('compound')
    op.drop_table('article')
    # ### end Alembic commands ###
