"""add journal method

Revision ID: 53c6e5d46e0b
Revises: 72abe11ff13d
Create Date: 2019-01-24 10:46:40.595973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c6e5d46e0b'
down_revision = '72abe11ff13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checker_article', sa.Column('journal_abbrev', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checker_article', 'journal_abbrev')
    # ### end Alembic commands ###
