"""empty message

Revision ID: 642c21265435
Revises: 0ead85f53d27
Create Date: 2018-10-24 15:58:52.101169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642c21265435'
down_revision = '0ead85f53d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('needs_work', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'needs_work')
    # ### end Alembic commands ###
