"""add resolution tracking

Revision ID: 67b3f402bf2b
Revises: dfac1b5d50c2
Create Date: 2019-01-30 15:23:11.590931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b3f402bf2b'
down_revision = 'dfac1b5d50c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checker_compound', sa.Column('resolve', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checker_compound', 'resolve')
    # ### end Alembic commands ###
