"""Added journal tables

Revision ID: 72abe11ff13d
Revises: d1e72c9c79d3
Create Date: 2019-01-23 16:36:17.162889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72abe11ff13d'
down_revision = 'd1e72c9c79d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal', sa.Text(), nullable=False),
    sa.Column('abbrev', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('altjournal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('altjournal', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('altjournal')
    op.drop_table('journal')
    # ### end Alembic commands ###
