"""Add NPAtlas tracking, remove `compound`.`curated_compound`'

Revision ID: 7c3fb6c4245b
Revises: b3e45f04efa1
Create Date: 2018-11-13 10:11:12.096691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c3fb6c4245b'
down_revision = 'b3e45f04efa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('npa_artid', sa.Integer(), nullable=True))
    op.add_column('compound', sa.Column('npaid', sa.Integer(), nullable=True))
    op.drop_column('compound', 'curated_compound')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compound', sa.Column('curated_compound', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('compound', 'npaid')
    op.drop_column('article', 'npa_artid')
    # ### end Alembic commands ###
