"""empty message

Revision ID: 893ffe555025
Revises: 249eaa378008
Create Date: 2018-10-24 10:35:51.645050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '893ffe555025'
down_revision = '249eaa378008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('instructions', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'instructions')
    # ### end Alembic commands ###
