"""empty message

Revision ID: a5f45e16bb38
Revises: 93bacd382830
Create Date: 2018-08-30 12:00:57.814153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f45e16bb38'
down_revision = '93bacd382830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'completed')
    # ### end Alembic commands ###
