"""empty message

Revision ID: afed26c5c264
Revises: 39105f0fa83d
Create Date: 2018-12-03 14:59:36.939405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afed26c5c264'
down_revision = '39105f0fa83d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('training', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'training')
    # ### end Alembic commands ###
