"""empty message

Revision ID: b3e45f04efa1
Revises: 7731946339c5
Create Date: 2018-10-26 11:39:24.087956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3e45f04efa1'
down_revision = '7731946339c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('is_nparticle', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'is_nparticle')
    # ### end Alembic commands ###
