"""add checker_compound

Revision ID: d1e72c9c79d3
Revises: 1857ed50f51e
Create Date: 2019-01-21 15:04:51.878810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e72c9c79d3'
down_revision = '1857ed50f51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checker_compound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('formula', sa.String(length=255), nullable=True),
    sa.Column('smiles', sa.Text(), nullable=True),
    sa.Column('inchi', sa.Text(), nullable=True),
    sa.Column('inchikey', sa.String(length=40), nullable=True),
    sa.Column('molblock', sa.Text(), nullable=True),
    sa.Column('source_genus', sa.String(length=255), nullable=True),
    sa.Column('source_species', sa.String(length=255), nullable=True),
    sa.Column('npaid', sa.Integer(), nullable=True),
    sa.Column('mibig_id', sa.Integer(), nullable=True),
    sa.Column('pubchem_id', sa.Integer(), nullable=True),
    sa.Column('berdy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['compound.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checker_compound')
    # ### end Alembic commands ###
