"""add genus tables

Revision ID: ee65cb5a3c85
Revises: 53c6e5d46e0b
Create Date: 2019-01-24 12:42:18.448253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee65cb5a3c85'
down_revision = '53c6e5d46e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genus', sa.String(length=255), nullable=False),
    sa.Column('genustype', sa.String(length=55), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('altgenus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genus_id', sa.Integer(), nullable=True),
    sa.Column('altgenus', sa.String(length=255), nullable=True),
    sa.Column('genustype', sa.String(length=55), nullable=True),
    sa.ForeignKeyConstraint(['genus_id'], ['genus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('altgenus')
    op.drop_table('genus')
    # ### end Alembic commands ###
